In [1]:
import json

candidates = []

with open("F:\\autorecruit-\\data_forensic _files\\candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        candidates.append(json.loads(line))

In [2]:
candidate_texts = []
candidate_ids = []

for c in candidates:

    skills = " ".join(
        [
            s["name"]
            for s in c["skills"]
        ]
    )

    career = " ".join(
        [
            job["description"]
            for job in c["career_history"]
        ]
    )

    summary = c["profile"]["summary"]

    title = c["profile"]["current_title"]

    text = f"""
    {title}

    {summary}

    {skills}

    {career}
    """

    candidate_texts.append(text)

    candidate_ids.append(
        c["candidate_id"]
    )

In [3]:
candidate_texts

["\n    Backend Engineer\n\n    Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.\n\n    Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP\n\n    Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure. Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.\n    ",
 "\n    Operations Manager\n\n    Professional with 12.5+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Project Management React Photoshop TypeScript Marketing Kafka JavaScript Feature Engineering GCP\n\n    Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise. Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up. Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality. Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design.\n    ",
 "\n    Customer Support\n\n    Professional with 1.1+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Angular SEO Excel Accounting Kubernetes Databricks\n\n    Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited.\n    ",
 "\n    Marketing Manager\n\n    Professional with 3.8+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Node.js Content Writing Redux Airflow GraphQL Object Detection Webpack Six Sigma SAP JavaScript\n\n    Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up. Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality. Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy, cost per order) and led the continuous improvement initiatives that drove a 22% productivity gain over 18 months.\n    ",
 "\n    Accountant\n\n    Professional with 11.0+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    SQL PowerPoint Photoshop Tailwind Apache Flink Image Classification\n\n    Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited. Senior accounting role at a mid-sized company — month-end close, financial reporting, statutory compliance (GAAP / Ind-AS), and tax filings. Owned the GL, fixed-asset register, and the audit-readiness function. Managed a team of 3 staff accountants. Built strong process discipline around the close cycle, reducing close time from 12 days to 7 over the last two years. Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited. Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.\n    ",
 "\n    Business Analyst\n\n    Professional with 6.0+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Content Writing SEO Redux SQL Sales gRPC Django Terraform\n\n    Senior accounting role at a mid-sized company — month-end close, financial reporting, statutory compliance (GAAP / Ind-AS), and tax filings. Owned the GL, fixed-asset register, and the audit-readiness function. Managed a team of 3 staff accountants. Built strong process discipline around the close cycle, reducing close time from 12 days to 7 over the last two years. Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited.\n    ",
 "\n    Civil Engineer\n\n    Professional with 5.5+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Content Writing MongoDB Sales Spark Scrum Apache Beam Illustrator\n\n    Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design. Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.\n    ",
 "\n    Operations Manager\n\n    Professional with 3.6+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Java BigQuery Spark Accounting Kubernetes TypeScript Rust HTML\n\n    Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and the SDR-handoff process. Recent focus has been on account-based marketing for our enterprise segment.\n    ",
 "\n    Mechanical Engineer\n\n    Professional with 11.0+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Snowflake gRPC JavaScript OpenCV Go PowerPoint\n\n    Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited. Marketing leadership role at a B2B SaaS company. Owned the demand-generation function — content marketing, paid acquisition, SEO, email nurture. Built and managed a team of 5 across content, performance marketing, and marketing operations. Worked closely with sales on lead-quality definitions and the SDR-handoff process. Recent focus has been on account-based marketing for our enterprise segment. Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up. Enterprise sales of cloud software solutions into the mid-market segment. Carried a $1.8M ARR quota and consistently delivered against it across the last three years. Owned the full sales cycle: prospecting, discovery, technical evaluation (with SE support), commercial negotiation, and close. Strong on consultative selling for technical buyers; comfortable engaging with both engineering and finance stakeholders.\n    ",
 "\n    Data Engineer\n\n    Software / data professional with 4.6 years of experience building data pipelines, backend systems, and analytics infrastructure. Most of my work has been data pipelines and analytics infrastructure; I've shipped a couple of small ML features but it's not the core of my day. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.\n\n    GCP Spring Boot Kubeflow Java GANs Figma Elasticsearch OpenCV CNN Azure Prompt Engineering Object Detection MLOps Python BM25 Weights & Biases Sales\n\n    Mixed data science and analytics-engineering role at a marketing-analytics startup. Spent maybe 30% of my time on lightweight ML (clustering, classification, churn prediction in sklearn/XGBoost) and 70% on data infrastructure and dashboards. Comfortable with the modeling work but I wouldn't call myself an ML specialist. Built our experimentation framework that supports the product team's A/B tests.\n    ",
 "\n    QA Engineer\n\n    Software engineer with 2.0 years of experience across web, backend, and cloud systems. Strong fundamentals in software development and system design. Most of my work is conventional backend engineering — APIs, databases, queues, deployments. I've been keeping up with AI/ML at a self-learner level — taken some online courses, played with the OpenAI and Anthropic APIs, built a small RAG side project — but I haven't done it in a professional capacity yet. Open to roles where I can either deepen my software engineering work or, if the team is open to it, start contributing to ML-adjacent systems.\n\n    Recommendation Systems Scrum FastAPI Hugging Face Transformers AWS Snowflake Spring Boot PostgreSQL Kubeflow Azure\n\n    Android mobile development using Java and (more recently) Kotlin at a consumer-app company. Built and maintained multiple production features including the main shopping flow, push notification system, and the offline-first sync layer. Comfortable with the Android framework, Jetpack components, and the typical patterns (MVVM, Hilt, Coroutines). My career has been entirely on mobile so far; interested in expanding into broader backend or platform engineering. Test automation and QA engineering for a fintech product. Built and maintained the end-to-end test suite using Selenium and pytest, plus the load-testing setup using Locust. Worked closely with developers on testability patterns and with product on acceptance criteria. Recent work has been on shifting test responsibility into the dev team — moving from QA-as-gate to QA-as-coach. Career has been entirely in QA/test engineering.\n    ",
 "\n    Operations Manager\n\n    Professional with 1.1+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    Azure Airflow AWS gRPC Vue.js dbt Agile PowerPoint Content Writing Project Management\n\n    Senior accounting role at a mid-sized company — month-end close, financial reporting, statutory compliance (GAAP / Ind-AS), and tax filings. Owned the GL, fixed-asset register, and the audit-readiness function. Managed a team of 3 staff accountants. Built strong process discipline around the close cycle, reducing close time from 12 days to 7 over the last two years.\n    ",
 "\n    Civil Engineer\n\n    Professional with 1.1+ years of experience. I'm a marketing manager with substantial experience in cross-functional collaboration, stakeholder management, and execution. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.\n\n    React Redux Vue.js Six Sigma Spring Boot Spark Data Pipelines GCP Flask Snowflake\n\n    Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.\n    ",

In [4]:
candidate_ids

['CAND_0000001',
 'CAND_0000002',
 'CAND_0000003',
 'CAND_0000004',
 'CAND_0000005',
 'CAND_0000006',
 'CAND_0000007',
 'CAND_0000008',
 'CAND_0000009',
 'CAND_0000010',
 'CAND_0000011',
 'CAND_0000012',
 'CAND_0000013',
 'CAND_0000014',
 'CAND_0000015',
 'CAND_0000016',
 'CAND_0000017',
 'CAND_0000018',
 'CAND_0000019',
 'CAND_0000020',
 'CAND_0000021',
 'CAND_0000022',
 'CAND_0000023',
 'CAND_0000024',
 'CAND_0000025',
 'CAND_0000026',
 'CAND_0000027',
 'CAND_0000028',
 'CAND_0000029',
 'CAND_0000030',
 'CAND_0000031',
 'CAND_0000032',
 'CAND_0000033',
 'CAND_0000034',
 'CAND_0000035',
 'CAND_0000036',
 'CAND_0000037',
 'CAND_0000038',
 'CAND_0000039',
 'CAND_0000040',
 'CAND_0000041',
 'CAND_0000042',
 'CAND_0000043',
 'CAND_0000044',
 'CAND_0000045',
 'CAND_0000046',
 'CAND_0000047',
 'CAND_0000048',
 'CAND_0000049',
 'CAND_0000050',
 'CAND_0000051',
 'CAND_0000052',
 'CAND_0000053',
 'CAND_0000054',
 'CAND_0000055',
 'CAND_0000056',
 'CAND_0000057',
 'CAND_0000058',
 'CAND_0000059',
 'CAND_0000060',
 'CAND_0000061',
 'CAND_0000062',
 'CAND_0000063',
 'CAND_0000064',
 'CAND_0000065',
 'CAND_0000066',
 'CAND_0000067',
 'CAND_0000068',
 'CAND_0000069',
 'CAND_0000070',
 'CAND_0000071',
 'CAND_0000072',
 'CAND_0000073',
 'CAND_0000074',
 'CAND_0000075',
 'CAND_0000076',
 'CAND_0000077',
 'CAND_0000078',
 'CAND_0000079',
 'CAND_0000080',
 'CAND_0000081',
 'CAND_0000082',
 'CAND_0000083',
 'CAND_0000084',
 'CAND_0000085',
 'CAND_0000086',
 'CAND_0000087',
 'CAND_0000088',
 'CAND_0000089',
 'CAND_0000090',
 'CAND_0000091',
 'CAND_0000092',
 'CAND_0000093',
 'CAND_0000094',
 'CAND_0000095',
 'CAND_0000096',
 'CAND_0000097',
 'CAND_0000098',
 'CAND_0000099',
 'CAND_0000100',
 'CAND_0000101',
 'CAND_0000102',
 'CAND_0000103',
 'CAND_0000104',
 'CAND_0000105',
 'CAND_0000106',
 'CAND_0000107',
 'CAND_0000108',
 'CAND_0000109',
 'CAND_0000110',
 'CAND_0000111',
 'CAND_0000112',
 'CAND_0000113',
 'CAND_0000114',
 'CAND_0000115',
 'CAND_0000116',
 'CAND_0000117',
 'CAND_0000118',
 'CAND_0000119',
 'CAND_0000120',
 'CAND_0000121',
 'CAND_0000122',
 'CAND_0000123',
 'CAND_0000124',
 'CAND_0000125',
 'CAND_0000126',
 'CAND_0000127',
 'CAND_0000128',
 'CAND_0000129',
 'CAND_0000130',
 'CAND_0000131',
 'CAND_0000132',
 'CAND_0000133',
 'CAND_0000134',
 'CAND_0000135',
 'CAND_0000136',
 'CAND_0000137',
 'CAND_0000138',
 'CAND_0000139',
 'CAND_0000140',
 'CAND_0000141',
 'CAND_0000142',
 'CAND_0000143',
 'CAND_0000144',
 'CAND_0000145',
 'CAND_0000146',
 'CAND_0000147',
 'CAND_0000148',
 'CAND_0000149',
 'CAND_0000150',
 'CAND_0000151',
 'CAND_0000152',
 'CAND_0000153',
 'CAND_0000154',
 'CAND_0000155',
 'CAND_0000156',
 'CAND_0000157',
 'CAND_0000158',
 'CAND_0000159',
 'CAND_0000160',
 'CAND_0000161',
 'CAND_0000162',
 'CAND_0000163',
 'CAND_0000164',
 'CAND_0000165',
 'CAND_0000166',
 'CAND_0000167',
 'CAND_0000168',
 'CAND_0000169',
 'CAND_0000170',
 'CAND_0000171',
 'CAND_0000172',
 'CAND_0000173',
 'CAND_0000174',
 'CAND_0000175',
 'CAND_0000176',
 'CAND_0000177',
 'CAND_0000178',
 'CAND_0000179',
 'CAND_0000180',
 'CAND_0000181',
 'CAND_0000182',
 'CAND_0000183',
 'CAND_0000184',
 'CAND_0000185',
 'CAND_0000186',
 'CAND_0000187',
 'CAND_0000188',
 'CAND_0000189',
 'CAND_0000190',
 'CAND_0000191',
 'CAND_0000192',
 'CAND_0000193',
 'CAND_0000194',
 'CAND_0000195',
 'CAND_0000196',
 'CAND_0000197',
 'CAND_0000198',
 'CAND_0000199',
 'CAND_0000200',
 'CAND_0000201',
 'CAND_0000202',
 'CAND_0000203',
 'CAND_0000204',
 'CAND_0000205',
 'CAND_0000206',
 'CAND_0000207',
 'CAND_0000208',
 'CAND_0000209',
 'CAND_0000210',
 'CAND_0000211',
 'CAND_0000212',
 'CAND_0000213',
 'CAND_0000214',
 'CAND_0000215',
 'CAND_0000216',
 'CAND_0000217',
 'CAND_0000218',
 'CAND_0000219',
 'CAND_0000220',
 'CAND_0000221',
 'CAND_0000222',
 'CAND_0000223',
 'CAND_0000224',
 'CAND_0000225',
 'CAND_0000226',
 'CAND_0000227',
 'CAND_0000228',
 'CAND_0000229',
 'CAND_0000230',
 'CAND_0000231',
 'CAND_0000232',
 'CAND_0000233',
 'CAND_0000234',
 'CAND_0000235',
 'CAND_0000236',
 'CAND_0000237',
 'CAND_0000238',
 'CAND_0000239',
 'CAND_0000240',
 'CAND_0000241',
 'CAND_0000242',
 'CAND_0000243',
 'CAND_0000244',
 'CAND_0000245',
 'CAND_0000246',
 'CAND_0000247',
 'CAND_0000248',
 'CAND_0000249',
 'CAND_0000250',
 'CAND_0000251',
 'CAND_0000252',
 'CAND_0000253',
 'CAND_0000254',
 'CAND_0000255',
 'CAND_0000256',
 'CAND_0000257',
 'CAND_0000258',
 'CAND_0000259',
 'CAND_0000260',
 'CAND_0000261',
 'CAND_0000262',
 'CAND_0000263',
 'CAND_0000264',
 'CAND_0000265',
 'CAND_0000266',
 'CAND_0000267',
 'CAND_0000268',
 'CAND_0000269',
 'CAND_0000270',
 'CAND_0000271',
 'CAND_0000272',
 'CAND_0000273',
 'CAND_0000274',
 'CAND_0000275',
 'CAND_0000276',
 'CAND_0000277',
 'CAND_0000278',
 'CAND_0000279',
 'CAND_0000280',
 'CAND_0000281',
 'CAND_0000282',
 'CAND_0000283',
 'CAND_0000284',
 'CAND_0000285',
 'CAND_0000286',
 'CAND_0000287',
 'CAND_0000288',
 'CAND_0000289',
 'CAND_0000290',
 'CAND_0000291',
 'CAND_0000292',
 'CAND_0000293',
 'CAND_0000294',
 'CAND_0000295',
 'CAND_0000296',
 'CAND_0000297',
 'CAND_0000298',
 'CAND_0000299',
 'CAND_0000300',
 'CAND_0000301',
 'CAND_0000302',
 'CAND_0000303',
 'CAND_0000304',
 'CAND_0000305',
 'CAND_0000306',
 'CAND_0000307',
 'CAND_0000308',
 'CAND_0000309',
 'CAND_0000310',
 'CAND_0000311',
 'CAND_0000312',
 'CAND_0000313',
 'CAND_0000314',
 'CAND_0000315',
 'CAND_0000316',
 'CAND_0000317',
 'CAND_0000318',
 'CAND_0000319',
 'CAND_0000320',
 'CAND_0000321',
 'CAND_0000322',
 'CAND_0000323',
 'CAND_0000324',
 'CAND_0000325',
 'CAND_0000326',
 'CAND_0000327',
 'CAND_0000328',
 'CAND_0000329',
 'CAND_0000330',
 'CAND_0000331',
 'CAND_0000332',
 'CAND_0000333',
 'CAND_0000334',
 'CAND_0000335',
 'CAND_0000336',
 'CAND_0000337',
 'CAND_0000338',
 'CAND_0000339',
 'CAND_0000340',
 'CAND_0000341',
 'CAND_0000342',
 'CAND_0000343',
 'CAND_0000344',
 'CAND_0000345',
 'CAND_0000346',
 'CAND_0000347',
 'CAND_0000348',
 'CAND_0000349',
 'CAND_0000350',
 'CAND_0000351',
 'CAND_0000352',
 'CAND_0000353',
 'CAND_0000354',
 'CAND_0000355',
 'CAND_0000356',
 'CAND_0000357',
 'CAND_0000358',
 'CAND_0000359',
 'CAND_0000360',
 'CAND_0000361',
 'CAND_0000362',
 'CAND_0000363',
 'CAND_0000364',
 'CAND_0000365',
 'CAND_0000366',
 'CAND_0000367',
 'CAND_0000368',
 'CAND_0000369',
 'CAND_0000370',
 'CAND_0000371',
 'CAND_0000372',
 'CAND_0000373',
 'CAND_0000374',
 'CAND_0000375',
 'CAND_0000376',
 'CAND_0000377',
 'CAND_0000378',
 'CAND_0000379',
 'CAND_0000380',
 'CAND_0000381',
 'CAND_0000382',
 'CAND_0000383',
 'CAND_0000384',
 'CAND_0000385',
 'CAND_0000386',
 'CAND_0000387',
 'CAND_0000388',
 'CAND_0000389',
 'CAND_0000390',
 'CAND_0000391',
 'CAND_0000392',
 'CAND_0000393',
 'CAND_0000394',
 'CAND_0000395',
 'CAND_0000396',
 'CAND_0000397',
 'CAND_0000398',
 'CAND_0000399',
 'CAND_0000400',
 'CAND_0000401',
 'CAND_0000402',
 'CAND_0000403',
 'CAND_0000404',
 'CAND_0000405',
 'CAND_0000406',
 'CAND_0000407',
 'CAND_0000408',
 'CAND_0000409',
 'CAND_0000410',
 'CAND_0000411',
 'CAND_0000412',
 'CAND_0000413',
 'CAND_0000414',
 'CAND_0000415',
 'CAND_0000416',
 'CAND_0000417',
 'CAND_0000418',
 'CAND_0000419',
 'CAND_0000420',
 'CAND_0000421',
 'CAND_0000422',
 'CAND_0000423',
 'CAND_0000424',
 'CAND_0000425',
 'CAND_0000426',
 'CAND_0000427',
 'CAND_0000428',
 'CAND_0000429',
 'CAND_0000430',
 'CAND_0000431',
 'CAND_0000432',
 'CAND_0000433',
 'CAND_0000434',
 'CAND_0000435',
 'CAND_0000436',
 'CAND_0000437',
 'CAND_0000438',
 'CAND_0000439',
 'CAND_0000440',
 'CAND_0000441',
 'CAND_0000442',
 'CAND_0000443',
 'CAND_0000444',
 'CAND_0000445',
 'CAND_0000446',
 'CAND_0000447',
 'CAND_0000448',
 'CAND_0000449',
 'CAND_0000450',
 'CAND_0000451',
 'CAND_0000452',
 'CAND_0000453',
 'CAND_0000454',
 'CAND_0000455',
 'CAND_0000456',
 'CAND_0000457',
 'CAND_0000458',
 'CAND_0000459',
 'CAND_0000460',
 'CAND_0000461',
 'CAND_0000462',
 'CAND_0000463',
 'CAND_0000464',
 'CAND_0000465',
 'CAND_0000466',
 'CAND_0000467',
 'CAND_0000468',
 'CAND_0000469',
 'CAND_0000470',
 'CAND_0000471',
 'CAND_0000472',
 'CAND_0000473',
 'CAND_0000474',
 'CAND_0000475',
 'CAND_0000476',
 'CAND_0000477',
 'CAND_0000478',
 'CAND_0000479',
 'CAND_0000480',
 'CAND_0000481',
 'CAND_0000482',
 'CAND_0000483',
 'CAND_0000484',
 'CAND_0000485',
 'CAND_0000486',
 'CAND_0000487',
 'CAND_0000488',
 'CAND_0000489',
 'CAND_0000490',
 'CAND_0000491',
 'CAND_0000492',
 'CAND_0000493',
 'CAND_0000494',
 'CAND_0000495',
 'CAND_0000496',
 'CAND_0000497',
 'CAND_0000498',
 'CAND_0000499',
 'CAND_0000500',
 'CAND_0000501',
 'CAND_0000502',
 'CAND_0000503',
 'CAND_0000504',
 'CAND_0000505',
 'CAND_0000506',
 'CAND_0000507',
 'CAND_0000508',
 'CAND_0000509',
 'CAND_0000510',
 'CAND_0000511',
 'CAND_0000512',
 'CAND_0000513',
 'CAND_0000514',
 'CAND_0000515',
 'CAND_0000516',
 'CAND_0000517',
 'CAND_0000518',
 'CAND_0000519',
 'CAND_0000520',
 'CAND_0000521',
 'CAND_0000522',
 'CAND_0000523',
 'CAND_0000524',
 'CAND_0000525',
 'CAND_0000526',
 'CAND_0000527',
 'CAND_0000528',
 'CAND_0000529',
 'CAND_0000530',
 'CAND_0000531',
 'CAND_0000532',
 'CAND_0000533',
 'CAND_0000534',
 'CAND_0000535',
 'CAND_0000536',
 'CAND_0000537',
 'CAND_0000538',
 'CAND_0000539',
 'CAND_0000540',
 'CAND_0000541',
 'CAND_0000542',
 'CAND_0000543',
 'CAND_0000544',
 'CAND_0000545',
 'CAND_0000546',
 'CAND_0000547',
 'CAND_0000548',
 'CAND_0000549',
 'CAND_0000550',
 'CAND_0000551',
 'CAND_0000552',
 'CAND_0000553',
 'CAND_0000554',
 'CAND_0000555',
 'CAND_0000556',
 'CAND_0000557',
 'CAND_0000558',
 'CAND_0000559',
 'CAND_0000560',
 'CAND_0000561',
 'CAND_0000562',
 'CAND_0000563',
 'CAND_0000564',
 'CAND_0000565',
 'CAND_0000566',
 'CAND_0000567',
 'CAND_0000568',
 'CAND_0000569',
 'CAND_0000570',
 'CAND_0000571',
 'CAND_0000572',
 'CAND_0000573',
 'CAND_0000574',
 'CAND_0000575',
 'CAND_0000576',
 'CAND_0000577',
 'CAND_0000578',
 'CAND_0000579',
 'CAND_0000580',
 'CAND_0000581',
 'CAND_0000582',
 'CAND_0000583',
 'CAND_0000584',
 'CAND_0000585',
 'CAND_0000586',
 'CAND_0000587',
 'CAND_0000588',
 'CAND_0000589',
 'CAND_0000590',
 'CAND_0000591',
 'CAND_0000592',
 'CAND_0000593',
 'CAND_0000594',
 'CAND_0000595',
 'CAND_0000596',
 'CAND_0000597',
 'CAND_0000598',
 'CAND_0000599',
 'CAND_0000600',
 'CAND_0000601',
 'CAND_0000602',
 'CAND_0000603',
 'CAND_0000604',
 'CAND_0000605',
 'CAND_0000606',
 'CAND_0000607',
 'CAND_0000608',
 'CAND_0000609',
 'CAND_0000610',
 'CAND_0000611',
 'CAND_0000612',
 'CAND_0000613',
 'CAND_0000614',
 'CAND_0000615',
 'CAND_0000616',
 'CAND_0000617',
 'CAND_0000618',
 'CAND_0000619',
 'CAND_0000620',
 'CAND_0000621',
 'CAND_0000622',
 'CAND_0000623',
 'CAND_0000624',
 'CAND_0000625',
 'CAND_0000626',
 'CAND_0000627',
 'CAND_0000628',
 'CAND_0000629',
 'CAND_0000630',
 'CAND_0000631',
 'CAND_0000632',
 'CAND_0000633',
 'CAND_0000634',
 'CAND_0000635',
 'CAND_0000636',
 'CAND_0000637',
 'CAND_0000638',
 'CAND_0000639',
 'CAND_0000640',
 'CAND_0000641',
 'CAND_0000642',
 'CAND_0000643',
 'CAND_0000644',
 'CAND_0000645',
 'CAND_0000646',
 'CAND_0000647',
 'CAND_0000648',
 'CAND_0000649',
 'CAND_0000650',
 'CAND_0000651',
 'CAND_0000652',
 'CAND_0000653',
 'CAND_0000654',
 'CAND_0000655',
 'CAND_0000656',
 'CAND_0000657',
 'CAND_0000658',
 'CAND_0000659',
 'CAND_0000660',
 'CAND_0000661',
 'CAND_0000662',
 'CAND_0000663',
 'CAND_0000664',
 'CAND_0000665',
 'CAND_0000666',
 'CAND_0000667',
 'CAND_0000668',
 'CAND_0000669',
 'CAND_0000670',
 'CAND_0000671',
 'CAND_0000672',
 'CAND_0000673',
 'CAND_0000674',
 'CAND_0000675',
 'CAND_0000676',
 'CAND_0000677',
 'CAND_0000678',
 'CAND_0000679',
 'CAND_0000680',
 'CAND_0000681',
 'CAND_0000682',
 'CAND_0000683',
 'CAND_0000684',
 'CAND_0000685',
 'CAND_0000686',
 'CAND_0000687',
 'CAND_0000688',
 'CAND_0000689',
 'CAND_0000690',
 'CAND_0000691',
 'CAND_0000692',
 'CAND_0000693',
 'CAND_0000694',
 'CAND_0000695',
 'CAND_0000696',
 'CAND_0000697',
 'CAND_0000698',
 'CAND_0000699',
 'CAND_0000700',
 'CAND_0000701',
 'CAND_0000702',
 'CAND_0000703',
 'CAND_0000704',
 'CAND_0000705',
 'CAND_0000706',
 'CAND_0000707',
 'CAND_0000708',
 'CAND_0000709',
 'CAND_0000710',
 'CAND_0000711',
 'CAND_0000712',
 'CAND_0000713',
 'CAND_0000714',
 'CAND_0000715',
 'CAND_0000716',
 'CAND_0000717',
 'CAND_0000718',
 'CAND_0000719',
 'CAND_0000720',
 'CAND_0000721',
 'CAND_0000722',
 'CAND_0000723',
 'CAND_0000724',
 'CAND_0000725',
 'CAND_0000726',
 'CAND_0000727',
 'CAND_0000728',
 'CAND_0000729',
 'CAND_0000730',
 'CAND_0000731',
 'CAND_0000732',
 'CAND_0000733',
 'CAND_0000734',
 'CAND_0000735',
 'CAND_0000736',
 'CAND_0000737',
 'CAND_0000738',
 'CAND_0000739',
 'CAND_0000740',
 'CAND_0000741',
 'CAND_0000742',
 'CAND_0000743',
 'CAND_0000744',
 'CAND_0000745',
 'CAND_0000746',
 'CAND_0000747',
 'CAND_0000748',
 'CAND_0000749',
 'CAND_0000750',
 'CAND_0000751',
 'CAND_0000752',
 'CAND_0000753',
 'CAND_0000754',
 'CAND_0000755',
 'CAND_0000756',
 'CAND_0000757',
 'CAND_0000758',
 'CAND_0000759',
 'CAND_0000760',
 'CAND_0000761',
 'CAND_0000762',
 'CAND_0000763',
 'CAND_0000764',
 'CAND_0000765',
 'CAND_0000766',
 'CAND_0000767',
 'CAND_0000768',
 'CAND_0000769',
 'CAND_0000770',
 'CAND_0000771',
 'CAND_0000772',
 'CAND_0000773',
 'CAND_0000774',
 'CAND_0000775',
 'CAND_0000776',
 'CAND_0000777',
 'CAND_0000778',
 'CAND_0000779',
 'CAND_0000780',
 'CAND_0000781',
 'CAND_0000782',
 'CAND_0000783',
 'CAND_0000784',
 'CAND_0000785',
 'CAND_0000786',
 'CAND_0000787',
 'CAND_0000788',
 'CAND_0000789',
 'CAND_0000790',
 'CAND_0000791',
 'CAND_0000792',
 'CAND_0000793',
 'CAND_0000794',
 'CAND_0000795',
 'CAND_0000796',
 'CAND_0000797',
 'CAND_0000798',
 'CAND_0000799',
 'CAND_0000800',
 'CAND_0000801',
 'CAND_0000802',
 'CAND_0000803',
 'CAND_0000804',
 'CAND_0000805',
 'CAND_0000806',
 'CAND_0000807',
 'CAND_0000808',
 'CAND_0000809',
 'CAND_0000810',
 'CAND_0000811',
 'CAND_0000812',
 'CAND_0000813',
 'CAND_0000814',
 'CAND_0000815',
 'CAND_0000816',
 'CAND_0000817',
 'CAND_0000818',
 'CAND_0000819',
 'CAND_0000820',
 'CAND_0000821',
 'CAND_0000822',
 'CAND_0000823',
 'CAND_0000824',
 'CAND_0000825',
 'CAND_0000826',
 'CAND_0000827',
 'CAND_0000828',
 'CAND_0000829',
 'CAND_0000830',
 'CAND_0000831',
 'CAND_0000832',
 'CAND_0000833',
 'CAND_0000834',
 'CAND_0000835',
 'CAND_0000836',
 'CAND_0000837',
 'CAND_0000838',
 'CAND_0000839',
 'CAND_0000840',
 'CAND_0000841',
 'CAND_0000842',
 'CAND_0000843',
 'CAND_0000844',
 'CAND_0000845',
 'CAND_0000846',
 'CAND_0000847',
 'CAND_0000848',
 'CAND_0000849',
 'CAND_0000850',
 'CAND_0000851',
 'CAND_0000852',
 'CAND_0000853',
 'CAND_0000854',
 'CAND_0000855',
 'CAND_0000856',
 'CAND_0000857',
 'CAND_0000858',
 'CAND_0000859',
 'CAND_0000860',
 'CAND_0000861',
 'CAND_0000862',
 'CAND_0000863',
 'CAND_0000864',
 'CAND_0000865',
 'CAND_0000866',
 'CAND_0000867',
 'CAND_0000868',
 'CAND_0000869',
 'CAND_0000870',
 'CAND_0000871',
 'CAND_0000872',
 'CAND_0000873',
 'CAND_0000874',
 'CAND_0000875',
 'CAND_0000876',
 'CAND_0000877',
 'CAND_0000878',
 'CAND_0000879',
 'CAND_0000880',
 'CAND_0000881',
 'CAND_0000882',
 'CAND_0000883',
 'CAND_0000884',
 'CAND_0000885',
 'CAND_0000886',
 'CAND_0000887',
 'CAND_0000888',
 'CAND_0000889',
 'CAND_0000890',
 'CAND_0000891',
 'CAND_0000892',
 'CAND_0000893',
 'CAND_0000894',
 'CAND_0000895',
 'CAND_0000896',
 'CAND_0000897',
 'CAND_0000898',
 'CAND_0000899',
 'CAND_0000900',
 'CAND_0000901',
 'CAND_0000902',
 'CAND_0000903',
 'CAND_0000904',
 'CAND_0000905',
 'CAND_0000906',
 'CAND_0000907',
 'CAND_0000908',
 'CAND_0000909',
 'CAND_0000910',
 'CAND_0000911',
 'CAND_0000912',
 'CAND_0000913',
 'CAND_0000914',
 'CAND_0000915',
 'CAND_0000916',
 'CAND_0000917',
 'CAND_0000918',
 'CAND_0000919',
 'CAND_0000920',
 'CAND_0000921',
 'CAND_0000922',
 'CAND_0000923',
 'CAND_0000924',
 'CAND_0000925',
 'CAND_0000926',
 'CAND_0000927',
 'CAND_0000928',
 'CAND_0000929',
 'CAND_0000930',
 'CAND_0000931',
 'CAND_0000932',
 'CAND_0000933',
 'CAND_0000934',
 'CAND_0000935',
 'CAND_0000936',
 'CAND_0000937',
 'CAND_0000938',
 'CAND_0000939',
 'CAND_0000940',
 'CAND_0000941',
 'CAND_0000942',
 'CAND_0000943',
 'CAND_0000944',
 'CAND_0000945',
 'CAND_0000946',
 'CAND_0000947',
 'CAND_0000948',
 'CAND_0000949',
 'CAND_0000950',
 'CAND_0000951',
 'CAND_0000952',
 'CAND_0000953',
 'CAND_0000954',
 'CAND_0000955',
 'CAND_0000956',
 'CAND_0000957',
 'CAND_0000958',
 'CAND_0000959',
 'CAND_0000960',
 'CAND_0000961',
 'CAND_0000962',
 'CAND_0000963',
 'CAND_0000964',
 'CAND_0000965',
 'CAND_0000966',
 'CAND_0000967',
 'CAND_0000968',
 'CAND_0000969',
 'CAND_0000970',
 'CAND_0000971',
 'CAND_0000972',
 'CAND_0000973',
 'CAND_0000974',
 'CAND_0000975',
 'CAND_0000976',
 'CAND_0000977',
 'CAND_0000978',
 'CAND_0000979',
 'CAND_0000980',
 'CAND_0000981',
 'CAND_0000982',
 'CAND_0000983',
 'CAND_0000984',
 'CAND_0000985',
 'CAND_0000986',
 'CAND_0000987',
 'CAND_0000988',
 'CAND_0000989',
 'CAND_0000990',
 'CAND_0000991',
 'CAND_0000992',
 'CAND_0000993',
 'CAND_0000994',
 'CAND_0000995',
 'CAND_0000996',
 'CAND_0000997',
 'CAND_0000998',
 'CAND_0000999',
 'CAND_0001000',
 ...]

In [5]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

embeddings = model.encode(
    candidate_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

c:\Users\kambl\AppData\Local\Programs\Python\Python313\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

WARNING:tensorflow:From c:\Users\kambl\AppData\Local\Programs\Python\Python313\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

In [6]:
embeddings.size

38400000

In [8]:
import hdbscan

clusterer = hdbscan.HDBSCAN(
    min_cluster_size=500,
    min_samples=20
)

labels = clusterer.fit_predict(
    embeddings
)

In [9]:
import pandas as pd

cluster_df = pd.DataFrame({
    "candidate_id": candidate_ids,
    "cluster": labels
})

In [10]:
cluster_df["cluster"].value_counts()

cluster
 0    68821
 1    25000
 2     5000
 3      998
-1      181
Name: count, dtype: int64

In [11]:
import pandas as pd

quality_rows = []

for c in candidates:

    s = c["redrob_signals"]

    quality_rows.append({

        "candidate_id":
        c["candidate_id"],

        "saved":
        s["saved_by_recruiters_30d"],

        "views":
        s["profile_views_received_30d"],

        "appearances":
        s["search_appearance_30d"],

        "connections":
        s["connection_count"],

        "endorsements":
        s["endorsements_received"],

        "completion":
        s["profile_completeness_score"],

        "interview":
        s["interview_completion_rate"]

    })

quality_df = pd.DataFrame(
    quality_rows
)

In [12]:
quality_df

,candidate_id,saved,views,appearances,connections,endorsements,completion,interview
0,CAND_0000001,4,23,249,356,35,86.9,0.71
1,CAND_0000002,10,7,107,179,3,78.7,0.62
2,CAND_0000003,4,1,28,19,46,31.9,0.86
3,CAND_0000004,8,3,5,485,22,28.5,0.35
4,CAND_0000005,1,12,67,300,14,84.6,0.74
...,...,...,...,...,...,...,...,...
99995,CAND_0099996,7,52,98,325,12,41.4,0.87
99996,CAND_0099997,0,42,49,292,10,42.7,0.38
99997,CAND_0099998,26,84,187,442,66,75.9,0.79
99998,CAND_0099999,3,81,102,345,10,49.1,0.49
99999,CAND_0100000,7,10,120,64,29,80.1,0.59

In [13]:
from sklearn.preprocessing import StandardScaler

features = [

    "saved",
    "views",
    "appearances",
    "connections",
    "endorsements",
    "completion",
    "interview"
]

X = StandardScaler().fit_transform(
    quality_df[features]
)

In [14]:
from sklearn.decomposition import PCA

pca = PCA(
    n_components=1
)

quality_df[
    "quality_score"
] = pca.fit_transform(X)

In [15]:
quality_df[
    "quality_score"
].describe()

count    1.000000e+05
mean    -1.250555e-17
std      1.409218e+00
min     -3.145835e+00
25%     -8.920829e-01
50%     -2.753696e-01
75%      5.528335e-01
max      1.771064e+01
Name: quality_score, dtype: float64

In [16]:
quality_df.sort_values(
    "quality_score",
    ascending=False
).head(50)

,candidate_id,saved,views,appearances,connections,endorsements,completion,interview,quality_score
93546,CAND_0093547,57,168,1340,989,242,62.6,0.97,17.710640
68350,CAND_0068351,66,179,1347,1255,100,94.5,0.95,16.470047
92277,CAND_0092278,1,327,1417,1307,223,65.4,0.78,15.639309
6566,CAND_0006567,76,167,1049,262,194,58.6,0.93,15.368776
80765,CAND_0080766,27,374,1105,767,182,92.0,0.88,15.336506
8424,CAND_0008425,55,260,1136,1421,97,57.2,0.77,15.046598
84818,CAND_0084819,50,99,1056,1497,174,95.2,0.82,14.412755
37979,CAND_0037980,65,249,748,1659,87,69.3,0.89,14.154163
83878,CAND_0083879,64,274,574,1486,140,59.6,0.83,14.068289
18498,CAND_0018499,16,75,1291,1839,189,98.0,0.80,13.572639
7410,CAND_0007411,3,113,1490,1285,224,58.9,0.80,13.438262
46063,CAND_0046064,25,323,802,1838,132,75.3,0.80,13.396779
28792,CAND_0028793,43,159,1096,640,179,95.9,0.70,13.346269
5259,CAND_0005260,11,331,1154,869,153,94.8,0.73,13.198734
27800,CAND_0027801,65,234,521,881,176,76.5,0.68,13.066513
71973,CAND_0071974,50,335,132,1898,167,87.1,0.85,12.991012
46524,CAND_0046525,38,108,663,1801,239,62.8,0.81,12.971044
10684,CAND_0010685,46,246,779,1202,123,70.7,0.89,12.794291
10256,CAND_0010257,35,269,890,737,145,85.1,0.92,12.695735
40886,CAND_0040887,50,114,846,1053,162,93.1,0.80,12.468258
39520,CAND_0039521,43,267,659,818,162,67.2,0.81,12.193788
76903,CAND_0076904,65,241,695,825,76,83.4,0.75,12.126350
19479,CAND_0019480,59,72,802,1364,125,78.6,0.84,12.069259
93911,CAND_0093912,56,292,773,581,52,87.8,0.96,11.946567
95618,CAND_0095619,55,94,1018,474,121,92.6,0.93,11.909059
88024,CAND_0088025,19,201,1398,1606,18,60.3,0.95,11.887221
70484,CAND_0070485,45,220,855,1335,89,55.7,0.71,11.882199
30826,CAND_0030827,50,127,990,617,144,79.0,0.61,11.860411
36183,CAND_0036184,30,139,971,1420,145,88.6,0.62,11.824319
93330,CAND_0093331,30,179,897,1261,127,77.4,0.98,11.718280
91533,CAND_0091534,49,210,713,1189,109,57.5,0.81,11.656762
81845,CAND_0081846,62,231,347,494,166,95.7,0.94,11.643411
86150,CAND_0086151,55,251,432,1442,109,77.2,0.60,11.488784
52681,CAND_0052682,16,290,850,1100,128,85.4,0.88,11.468993
32806,CAND_0032807,50,38,999,1145,127,66.6,0.74,11.372922
5537,CAND_0005538,20,322,1147,416,68,88.2,0.76,11.245654
36999,CAND_0037000,20,223,942,705,168,75.3,0.62,11.083634
61256,CAND_0061257,80,236,80,1513,56,93.3,0.80,10.916964
64903,CAND_0064904,39,92,942,1102,119,69.6,0.85,10.858603
78491,CAND_0078492,9,299,1014,1363,69,58.5,0.89,10.846158
51614,CAND_0051615,42,215,693,1385,66,75.3,0.89,10.839825
49539,CAND_0049540,43,123,693,993,138,96.5,0.89,10.819189
20876,CAND_0020877,19,300,781,832,137,65.2,0.75,10.784814
49895,CAND_0049896,44,275,1097,277,15,83.2,0.68,10.779867
49537,CAND_0049538,60,5,996,1242,79,52.9,0.67,10.648428
53590,CAND_0053591,40,59,605,1465,172,71.5,0.97,10.629231
13535,CAND_0013536,36,287,1017,290,58,54.2,0.78,10.604839
48468,CAND_0048469,39,155,713,813,138,83.4,0.89,10.569266
50552,CAND_0050553,50,164,632,847,133,87.2,0.52,10.559150
39753,CAND_0039754,51,279,541,1009,46,67.1,0.98,10.558153

In [64]:
honeypot_scores = []
data = pd.read_csv("candidate_behavior_scores_full.csv")

for idx, c in enumerate(candidates):
    score = 0
    
    # Get the corresponding row from data
    candidate_id = c["candidate_id"]
    candidate_data = data[data["candidate_id"] == candidate_id]
    
    if candidate_data.empty:
        honeypot_scores.append(0)
        continue
    
    row = candidate_data.iloc[0]
    
    if row["date_anomaly"]:
        score += 3
    
    if row["education_score"] < 1:
        score += 2
    
    if pd.notna(row.get("skill_anomaly")) and row["skill_anomaly"]:
        score += 2
    
    if pd.notna(row.get("skill_desc_similarity")):
        if row["skill_desc_similarity"] < 0.05:
            score += 3
        elif row["skill_desc_similarity"] < 0.10:
            score += 2
        elif row["skill_desc_similarity"] < 0.20:
            score += 1
    
    honeypot_scores.append({
        "candidate_id" : c["candidate_id"],
        "honeypot_score" : score})

C:\Users\kambl\AppData\Local\Temp\ipykernel_8360\3851820416.py:2: DtypeWarning: Columns (0: skill_anomaly_x, 1: skill_anomaly_y) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("candidate_behavior_scores_full.csv")

In [65]:
honeypot_scores_df = pd.DataFrame(honeypot_scores)

honeypot_scores_df.describe()

       honeypot_score
count   100000.000000
mean         0.725930
std          1.176227
min          0.000000
25%          0.000000
50%          0.000000
75%          2.000000
max          8.000000

In [66]:
honeypot_scores_df

       candidate_id  honeypot_score
0      CAND_0000001               1
1      CAND_0000002               0
2      CAND_0000003               0
3      CAND_0000004               3
4      CAND_0000005               2
...             ...             ...
99995  CAND_0099996               0
99996  CAND_0099997               0
99997  CAND_0099998               2
99998  CAND_0099999               0
99999  CAND_0100000               2

[100000 rows x 2 columns]

In [56]:
honeypot_labels = []
for s in honeypot_scores:

    if s["score"] == 0:
        honeypot_labels.append({
            "candidate_id": s["candidate_id"],
            "honey_pot_labels": "trusted"
        })

    elif s["score"] <= 2:
        honeypot_labels.append({
            "candidate_id": s["candidate_id"],
            "honey_pot_labels": "minor_issue"
        })

    elif s["score"] <= 5:
        honeypot_labels.append({
            "candidate_id": s["candidate_id"],
            "honey_pot_labels": "suspicious"
        })
    else:
        honeypot_labels.append({
            "candidate_id": s["candidate_id"],
            "honey_pot_labels": "high_risk"
        })

In [67]:
honeypot_labels_df = pd.DataFrame(honeypot_labels)
honeypot_labels_df

       candidate_id honey_pot_labels
0      CAND_0000001      minor_issue
1      CAND_0000002          trusted
2      CAND_0000003          trusted
3      CAND_0000004       suspicious
4      CAND_0000005      minor_issue
...             ...              ...
99995  CAND_0099996          trusted
99996  CAND_0099997          trusted
99997  CAND_0099998      minor_issue
99998  CAND_0099999          trusted
99999  CAND_0100000      minor_issue

[100000 rows x 2 columns]

In [68]:
honeypot_scores_df = honeypot_scores_df.merge(
    honeypot_labels_df,
    on="candidate_id",
    how="left"
)

In [69]:
honeypot_scores_df

       candidate_id  honeypot_score honey_pot_labels
0      CAND_0000001               1      minor_issue
1      CAND_0000002               0          trusted
2      CAND_0000003               0          trusted
3      CAND_0000004               3       suspicious
4      CAND_0000005               2      minor_issue
...             ...             ...              ...
99995  CAND_0099996               0          trusted
99996  CAND_0099997               0          trusted
99997  CAND_0099998               2      minor_issue
99998  CAND_0099999               0          trusted
99999  CAND_0100000               2      minor_issue

[100000 rows x 3 columns]

In [70]:
honeypot_scores_df.columns.tolist()

['candidate_id', 'honeypot_score', 'honey_pot_labels']

In [71]:
honeypot_scores_df.head(20)

    candidate_id  honeypot_score honey_pot_labels
0   CAND_0000001               1      minor_issue
1   CAND_0000002               0          trusted
2   CAND_0000003               0          trusted
3   CAND_0000004               3       suspicious
4   CAND_0000005               2      minor_issue
5   CAND_0000006               6        high_risk
6   CAND_0000007               1      minor_issue
7   CAND_0000008               1      minor_issue
8   CAND_0000009               3       suspicious
9   CAND_0000010               0          trusted
10  CAND_0000011               0          trusted
11  CAND_0000012               3       suspicious
12  CAND_0000013               5       suspicious
13  CAND_0000014               0          trusted
14  CAND_0000015               3       suspicious
15  CAND_0000016               1      minor_issue
16  CAND_0000017               1      minor_issue
17  CAND_0000018               1      minor_issue
18  CAND_0000019               3       suspicious
19  CAND_0000020               2      minor_issue

In [75]:
behavior_df = pd.read_csv("candidate_behavior_scores_full.csv")

behavior_df = behavior_df.merge(
    honeypot_scores_df[["candidate_id", "honeypot_score"]],
    on="candidate_id",
    how="left"
)
behavior_df = behavior_df.merge(
    honeypot_scores_df[["candidate_id", "honey_pot_labels"]],
    on="candidate_id",
    how="left"
)

behavior_df.to_csv("candidate_behavior_scores_full.csv", index=False)

print(behavior_df.head())
print(behavior_df.shape)

C:\Users\kambl\AppData\Local\Temp\ipykernel_8360\1590361298.py:1: DtypeWarning: Columns (0: skill_anomaly_x, 1: skill_anomaly_y) have mixed types. Specify dtype option on import or set low_memory=False.
  behavior_df = pd.read_csv("candidate_behavior_scores_full.csv")

   candidate_id  profile_completeness  open_to_work  response_rate  \
0  CAND_0000001                  86.9          True           0.34
1  CAND_0000002                  78.7          True           0.29
2  CAND_0000003                  31.9         False           0.46
3  CAND_0000004                  28.5         False           0.26
4  CAND_0000005                  84.6          True           0.37

   response_time  views  applications  connections  search_appearance  saved  \
0          177.8     23             2          356                249      4
1          171.6      7             1          179                107     10
2          119.4      1             9           19                 28      4
3          104.1      3             9          485                  5      8
4          116.7     12             2          300                 67      1

   ...  skill_desc_similarity_x  date_anomaly  education_score_y  \
0  ...                 0.156749         False                1.0
1  ...                 0.252431         False                1.0
2  ...                 0.223676         False                1.0
3  ...                 0.137554         False                0.5
4  ...                 0.073007         False                1.0

   skill_anomaly_x  education_score  skill_desc_similarity_y  \
0              NaN              1.0                 0.156749
1              NaN              1.0                 0.252431
2              NaN              1.0                 0.223676
3              NaN              0.5                 0.137554
4             True              1.0                 0.073007

   skill_desc_similarity  skill_anomaly_y  honeypot_score  honey_pot_labels
0               0.156749              NaN               1       minor_issue
1               0.252431              NaN               0           trusted
2               0.223676              NaN               0           trusted
3               0.137554              NaN               3        suspicious
4               0.073007             True               2       minor_issue

[5 rows x 36 columns]
(100000, 36)

In [76]:
df = pd.read_csv("candidate_behavior_scores_full.csv")

C:\Users\kambl\AppData\Local\Temp\ipykernel_8360\3533008024.py:1: DtypeWarning: Columns (0: skill_anomaly_x, 1: skill_anomaly_y) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("candidate_behavior_scores_full.csv")

In [78]:
cols_to_keep = [

    "candidate_id",

    # behavior
    "behavior_score",
    "availability_score",
    "responsiveness_score",
    "demand_score",
    "reliability_score",

    # trust
    "date_anomaly",
    "education_score",
    "skill_desc_similarity",
    "skill_anomaly_y",

    # profile
    "profile_completeness",

    # honeypot
    "honeypot_score",
    "honey_pot_labels"
]

master_df = df[cols_to_keep].copy()

In [79]:
master_df

,candidate_id,behavior_score,availability_score,responsiveness_score,demand_score,reliability_score,date_anomaly,education_score,skill_desc_similarity,skill_anomaly_y,profile_completeness,honeypot_score,honey_pot_labels
0,CAND_0000001,0.489693,0.84,0.347500,0.076872,0.658,False,1.0,0.156749,NaN,86.9,1,minor_issue
1,CAND_0000002,NaN,0.84,0.319143,0.082477,NaN,False,1.0,0.252431,NaN,78.7,0,trusted
2,CAND_0000003,NaN,0.00,0.494071,0.029561,NaN,False,1.0,0.223676,NaN,31.9,0,trusted
3,CAND_0000004,NaN,0.08,0.370464,0.053078,NaN,False,0.5,0.137554,NaN,28.5,3,suspicious
4,CAND_0000005,NaN,0.92,0.433964,0.024869,NaN,False,1.0,0.073007,True,84.6,2,minor_issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CAND_0099996,NaN,0.32,0.336643,0.098616,NaN,False,1.0,NaN,NaN,41.4,0,trusted
99996,CAND_0099997,NaN,0.92,0.470643,0.040267,NaN,False,1.0,NaN,NaN,42.7,0,trusted
99997,CAND_0099998,0.361263,0.16,0.382071,0.254980,0.770,False,0.5,NaN,NaN,75.9,2,minor_issue
99998,CAND_0099999,0.490984,0.68,0.607321,0.097415,0.554,False,1.0,NaN,NaN,49.1,0,trusted
99999,CAND_0100000,NaN,0.08,0.134571,0.067879,NaN,False,0.5,NaN,NaN,80.1,2,minor_issue

In [80]:
quality_features = [

    "profile_completeness",

    "views",

    "search_appearance",

    "saved",

    "connections",

    "completion_rate"
]

In [83]:
from sklearn.preprocessing import StandardScaler

X = df[quality_features]

X_scaled = StandardScaler().fit_transform(X)

In [84]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)

quality_score = pca.fit_transform(X_scaled)

df["quality_score"] = quality_score

In [85]:
df["quality_score"].describe()

count    1.000000e+05
mean     1.080025e-17
std      1.336318e+00
min     -3.120069e+00
25%     -8.546907e-01
50%     -2.394517e-01
75%      5.467699e-01
max      1.639319e+01
Name: quality_score, dtype: float64

In [86]:
master_df = df[
[
    "candidate_id",

    "quality_score",

    "behavior_score",

    "education_score",

    "skill_desc_similarity",

    "honeypot_score",

    "honey_pot_labels"
]
].copy()

In [88]:
master_df["forensic_rank_score"] = (

      0.35 * master_df["quality_score"]

    + 0.30 * master_df["behavior_score"]

    + 0.20 * master_df["skill_desc_similarity"]

    + 0.15 * master_df["education_score"]

    - 0.10 * master_df["honeypot_score"]

)

In [89]:
top100 = (
    master_df
    .sort_values(
        "forensic_rank_score",
        ascending=False
    )
    .head(100)
)

top100.head(20)

,candidate_id,quality_score,behavior_score,education_score,skill_desc_similarity,honeypot_score,honey_pot_labels,forensic_rank_score
30,CAND_0000031,7.405954,0.653590,1.0,0.212809,0,trusted,2.980723
81,CAND_0000082,3.051655,0.587741,0.5,0.094025,4,suspicious,0.938207
62,CAND_0000063,1.586213,0.598290,1.0,0.246967,0,trusted,0.934055
53,CAND_0000054,0.856366,0.470941,1.0,0.233326,0,trusted,0.637675
0,CAND_0000001,0.643806,0.489693,1.0,0.156749,1,minor_issue,0.453590
87,CAND_0000088,0.301155,0.396510,1.0,0.208540,0,trusted,0.416065
50,CAND_0000051,0.462023,0.581927,1.0,0.137119,1,minor_issue,0.413710
17,CAND_0000018,0.568241,0.250412,1.0,0.199216,1,minor_issue,0.363851
35,CAND_0000036,0.533972,0.483935,1.0,0.091147,2,minor_issue,0.300300
84,CAND_0000085,0.160012,0.388566,1.0,0.184668,1,minor_issue,0.259507
36,CAND_0000037,0.447602,0.415991,1.0,0.063283,2,minor_issue,0.244115
82,CAND_0000083,-0.063910,0.256046,1.0,0.144153,1,minor_issue,0.133276
26,CAND_0000027,0.069137,0.531406,0.5,0.303020,2,minor_issue,0.119224
55,CAND_0000056,-0.619582,0.336782,1.0,0.371983,0,trusted,0.108578
69,CAND_0000070,0.209650,0.217608,1.0,0.080049,2,minor_issue,0.104670
45,CAND_0000046,0.443350,0.294304,0.0,0.290637,2,minor_issue,0.101591
47,CAND_0000048,-0.496436,0.472766,1.0,0.108354,1,minor_issue,0.039748
67,CAND_0000068,-0.248863,0.553346,0.5,0.332590,2,minor_issue,0.020420
31,CAND_0000032,-0.109910,0.317826,0.5,0.294894,2,minor_issue,-0.009142
57,CAND_0000058,-0.605060,0.393364,1.0,0.164109,1,minor_issue,-0.010940

In [90]:
from sklearn.preprocessing import MinMaxScaler

cols = [

    "quality_score",
    "behavior_score",
    "education_score",
    "skill_desc_similarity"

]

scaler = MinMaxScaler()

master_df[
    [f"{c}_norm" for c in cols]
] = scaler.fit_transform(
    master_df[cols]
)

In [95]:
master_df["forensic_rank_score"] = (

      0.35 * master_df["quality_score_norm"]

    + 0.30 * master_df["behavior_score_norm"]

    + 0.20 * master_df["skill_desc_similarity_norm"]

    + 0.15 * master_df["education_score_norm"]

    - 0.25 * (
        master_df["honeypot_score"] /
        master_df["honeypot_score"].max()
      )

)

In [97]:
top100 = (
    master_df
    .sort_values(
        "forensic_rank_score",
        ascending=False
    )
    .head(100)
)

top100.head(30)

,candidate_id,quality_score,behavior_score,education_score,skill_desc_similarity,honeypot_score,honey_pot_labels,forensic_rank_score,quality_score_norm,behavior_score_norm,education_score_norm,skill_desc_similarity_norm
30,CAND_0000031,7.405954,0.653590,1.0,0.212809,0,trusted,0.678438,0.539429,0.763995,1.0,0.552195
62,CAND_0000063,1.586213,0.598290,1.0,0.246967,0,trusted,0.570055,0.241184,0.687269,1.0,0.647301
53,CAND_0000054,0.856366,0.470941,1.0,0.233326,0,trusted,0.496361,0.203781,0.510579,1.0,0.609322
55,CAND_0000056,-0.619582,0.336782,1.0,0.371983,0,trusted,0.491259,0.128143,0.324440,1.0,0.995386
50,CAND_0000051,0.462023,0.581927,1.0,0.137119,1,minor_issue,0.450660,0.183572,0.664567,1.0,0.341449
87,CAND_0000088,0.301155,0.396510,1.0,0.208540,0,trusted,0.441620,0.175328,0.407311,1.0,0.540308
67,CAND_0000068,-0.248863,0.553346,0.5,0.332590,2,minor_issue,0.428614,0.147141,0.624912,0.5,0.885702
0,CAND_0000001,0.643806,0.489693,1.0,0.156749,1,minor_issue,0.426461,0.192888,0.536597,1.0,0.396108
86,CAND_0000087,-0.742568,0.476295,1.0,0.180390,1,minor_issue,0.409182,0.121840,0.518008,1.0,0.461929
26,CAND_0000027,0.069137,0.531406,0.5,0.303020,2,minor_issue,0.408719,0.163438,0.594472,0.5,0.803371
84,CAND_0000085,0.160012,0.388566,1.0,0.184668,1,minor_issue,0.391238,0.168095,0.396288,1.0,0.473841
47,CAND_0000048,-0.496436,0.472766,1.0,0.108354,1,minor_issue,0.372014,0.134454,0.513112,1.0,0.261359
57,CAND_0000058,-0.605060,0.393364,1.0,0.164109,1,minor_issue,0.368064,0.128887,0.402945,1.0,0.416600
35,CAND_0000036,0.533972,0.483935,1.0,0.091147,2,minor_issue,0.354313,0.187259,0.528608,1.0,0.213449
17,CAND_0000018,0.568241,0.250412,1.0,0.199216,1,minor_issue,0.349157,0.189016,0.204607,1.0,0.514348
46,CAND_0000047,-0.745209,0.257165,1.0,0.189983,1,minor_issue,0.323268,0.121705,0.213975,1.0,0.488641
31,CAND_0000032,-0.109910,0.317826,0.5,0.294894,2,minor_issue,0.312083,0.154262,0.298139,0.5,0.780745
82,CAND_0000083,-0.063910,0.256046,1.0,0.144153,1,minor_issue,0.309501,0.156620,0.212423,1.0,0.361034
36,CAND_0000037,0.447602,0.415991,1.0,0.063283,2,minor_issue,0.308967,0.182833,0.434339,1.0,0.135869
40,CAND_0000041,-0.320698,0.408819,1.0,0.092529,2,minor_issue,0.308487,0.143460,0.424388,1.0,0.217297
81,CAND_0000082,3.051655,0.587741,0.5,0.094025,4,suspicious,0.306782,0.316284,0.672633,0.5,0.221462
39,CAND_0000040,-0.864629,0.278012,1.0,0.143687,1,minor_issue,0.304022,0.115585,0.242900,1.0,0.359737
93,CAND_0000094,-0.136812,0.271510,1.0,0.204159,3,suspicious,0.285545,0.152884,0.233878,1.0,0.528110
68,CAND_0000069,-0.249241,0.482999,1.0,0.049154,3,suspicious,0.285241,0.147122,0.527310,1.0,0.096528
83,CAND_0000084,-0.828958,0.444098,0.5,0.169425,3,suspicious,0.250625,0.117413,0.473337,0.5,0.431399
85,CAND_0000086,-1.004447,0.303801,1.0,0.076252,2,minor_issue,0.243447,0.108420,0.278681,1.0,0.171978
45,CAND_0000046,0.443350,0.294304,0.0,0.290637,2,minor_issue,0.234845,0.182615,0.265505,0.0,0.768892
16,CAND_0000017,-2.450827,0.176793,1.0,0.141417,1,minor_issue,0.232176,0.034297,0.102463,1.0,0.353418
69,CAND_0000070,0.209650,0.217608,1.0,0.080049,2,minor_issue,0.231461,0.170639,0.159092,1.0,0.182550
70,CAND_0000071,-0.128681,0.220027,1.0,0.083838,2,minor_issue,0.228509,0.153300,0.162449,1.0,0.193098

In [101]:
top20 = (
    master_df
    .sort_values(
        "forensic_rank_score",
        ascending=False
    )
    .head(100)
)

top20["honey_pot_labels"].value_counts()

honey_pot_labels
minor_issue    46
suspicious     30
trusted        22
high_risk       2
Name: count, dtype: int64

In [102]:
def trust_multiplier(label):

    if label == "trusted":
        return 1.00

    elif label == "minor_issue":
        return 0.90

    elif label == "suspicious":
        return 0.70

    elif label == "high_risk":
        return 0.40

    return 1.00

In [103]:
top50_ids = (
    master_df
    .sort_values(
        "forensic_rank_score",
        ascending=False
    )
    .head(50)["candidate_id"]
)

In [104]:
top50_ids

30    CAND_0000031
62    CAND_0000063
53    CAND_0000054
55    CAND_0000056
50    CAND_0000051
87    CAND_0000088
67    CAND_0000068
0     CAND_0000001
86    CAND_0000087
26    CAND_0000027
84    CAND_0000085
47    CAND_0000048
57    CAND_0000058
35    CAND_0000036
17    CAND_0000018
46    CAND_0000047
31    CAND_0000032
82    CAND_0000083
36    CAND_0000037
40    CAND_0000041
81    CAND_0000082
39    CAND_0000040
93    CAND_0000094
68    CAND_0000069
83    CAND_0000084
85    CAND_0000086
45    CAND_0000046
16    CAND_0000017
69    CAND_0000070
70    CAND_0000071
27    CAND_0000028
73    CAND_0000074
72    CAND_0000073
8     CAND_0000009
74    CAND_0000075
12    CAND_0000013
91    CAND_0000092
94    CAND_0000095
1     CAND_0000002
2     CAND_0000003
3     CAND_0000004
4     CAND_0000005
5     CAND_0000006
6     CAND_0000007
7     CAND_0000008
9     CAND_0000010
10    CAND_0000011
11    CAND_0000012
13    CAND_0000014
14    CAND_0000015
Name: candidate_id, dtype: str